public enum States {
    IDLE, SCHEDULING, HANDLING_RECEIVED_MESSAGE, SENDING_TASK, RECEIVING_TASK, SENDING_MESSAGE, RECEIVING_MESSAGE, WAITING_FOR_TASK, ADDING_TO_QUEUE, GOING_UP, GOING_DOWN, OUT_OF_SERVICE
}
